//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.USER
{
    public partial class CompanyPublic
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;

        protected global::System.Web.UI.WebControls.Literal litVerified;
        protected global::System.Web.UI.WebControls.Panel pnlMissing;
        protected global::System.Web.UI.WebControls.Panel pnlBody;
        protected global::System.Web.UI.WebControls.Literal litIndustry;
        protected global::System.Web.UI.WebControls.Literal litDesc;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liSite;
        protected global::System.Web.UI.WebControls.HyperLink hypWebsite;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liEmail;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLoc;
        protected global::System.Web.UI.WebControls.Literal litLoc;
        protected global::System.Web.UI.WebControls.HyperLink hypMsgCompany;
    }
}
