//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace CareerConnect.USER.Employer
{
    public partial class EmployerMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton lbCompany;
        protected global::System.Web.UI.WebControls.LinkButton lbLoginorLogout;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navDash;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navMyJobs;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navPost;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl navApps;
        protected global::System.Web.UI.WebControls.Literal litCcMsgState;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
