//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.USER
{


    public partial class job_listing
    {

        /// <summary>
        /// rptJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtKeyword;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryFilter;
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlJobTypeFilter;
        protected global::System.Web.UI.WebControls.TextBox txtSalMin;
        protected global::System.Web.UI.WebControls.TextBox txtSalMax;
        protected global::System.Web.UI.WebControls.DropDownList ddlPosted;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Literal litResultSummary;
        protected global::System.Web.UI.WebControls.Panel pnlPager;
        protected global::System.Web.UI.WebControls.Button btnPrev;
        protected global::System.Web.UI.WebControls.Literal litPageLabel;
        protected global::System.Web.UI.WebControls.Button btnNext;

        protected global::System.Web.UI.WebControls.Repeater rptJobs;

        protected global::System.Web.UI.WebControls.Panel pnlRecommendations;

        protected global::System.Web.UI.WebControls.Repeater rptRecommended;

        /// <summary>
        /// pnlNoJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlNoJobs;
    }
}

