//------------------------------------------------------------------------------
// <auto-generated />
//------------------------------------------------------------------------------

namespace CareerConnect.USER.Employer
{
    public partial class EmployerMessages
    {
        protected global::System.Web.UI.WebControls.Repeater rptThreads;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
